services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: email_sender
      POSTGRES_USER: email_sender
      POSTGRES_PASSWORD: email_sender
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://email_sender:email_sender@db:5432/email_sender
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      SECRET_KEY: dev-only-change-me
      DEBUG: "True"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://email_sender:email_sender@db:5432/email_sender
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      SECRET_KEY: dev-only-change-me
      DEBUG: "True"
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
